### ISSUE TITLE
[Enhancement] Improve the OSGi manager to not install old versions of plugins

### ISSUE THREAD

**Issue by twasyl** [twasyl/SlideshowFX#15]
Currently the OSGi manager loads all plugins for the application, with no distinction of versioning. This means that if a plugin A in version X and in version Y is available, both will be loaded by the application.

A mechanism should take the versions of plugins in consideration in order to only load the most recent. This will be mandatory for releasing new plugins' versions.

**Comment by Hillrunner2008** [comment]
For your consideration (https://bitbucket.org/lorainelab/integrated-genome-browser/src/a07386588814478d117fbd8fe2d836e49ffba9c7/plugins/plugin-manager/src/main/java/org/lorainelab/igb/plugin/manager/BundleInfoManager.java?at=master&fileviewer=file-view-default).  This osgi bundle provides plugin manager capabilities to a modular swing application built for visualizing genomic data.  The project is now deprecated with a javafx based replacement in the works, but some of the general functionality is likely useful as a reference.

screenshot 
![plugin-manager](https://cloud.githubusercontent.com/assets/1864452/19444636/3c1c6624-945f-11e6-967d-979d690b2bbe.png)

**Comment by twasyl** [comment]
Thank you for pointing this out. I had approximately the same idea for managing the versions.
